"""Add page depth

Revision ID: 81db0a0d527d
Revises: 8410e51a60e3
Create Date: 2026-09-12 22:13:30.501030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81db0a0d527d'
down_revision: Union[str, Sequence[str], None] = '8410e51a60e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('depth', sa.Integer(), nullable=False))
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=2048),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('final_url',
               existing_type=sa.VARCHAR(length=2048),
               type_=sa.Text(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('screenshot_path',
               existing_type=sa.VARCHAR(length=2048),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_pages_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pages_test_run_id'), ['test_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pages_test_run_id'))
        batch_op.drop_index(batch_op.f('ix_pages_project_id'))
        batch_op.alter_column('screenshot_path',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=2048),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('final_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=2048),
               nullable=False)
        batch_op.alter_column('url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=2048),
               existing_nullable=False)
        batch_op.drop_column('depth')

    # ### end Alembic commands ###
